auto: true
server: true
pygments: true
permalink: none
root_dir: "poole"
oauth_client_id: caf55c20366465a1332d
gatekeeper_url: http://poole-oauth-staging.herokuapp.com
exclude:
- .gitignore
- README.md